### ISSUE TITLE
app is not running

### ISSUE THREAD

**Issue by bankotigaurav** [coding-blocks-archives/Vue_Typescript_Todolist#4]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-ts-todo@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-ts-todo@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-ts-todo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-ts-todo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-ts-todo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gaurav.bankoti\Desktop\Vue_Typescript_Todolist\npm-debug.log

**Comment by championswimmer** [comment]
use node 8.x
